"""
Standalone tangent-ogive CAD generator using the Gmsh Python API.

This script does NOT use main.py or ogive_mesh.py.
It only creates an ogive CAD model and exports it as a STEP file.

Geometry:
    (x + R - D/2)^2 + z^2 = R^2
    R = D * ((L/D)^2 + 1/4)

Behavior:
    t = 0.0  -> zero-thickness open ogive surface
    t > 0.0  -> finite-thickness 3-D solid

Units:
    mm
"""

import math
from pathlib import Path

try:
    import gmsh
except ImportError as exc:
    raise ImportError(
        "The Gmsh Python module is required.\n"
        "Install it with:\n"
        "    pip install gmsh"
    ) from exc


# ============================================================
# USER PARAMETERS
# ============================================================

D = 110.0          # Outer base diameter [mm]
L = 200.0          # Outer ogive height [mm]
t = 3.0            # Wall thickness [mm]
                    # t = 0.0 -> surface only
                    # t > 0.0 -> 3-D solid

OUTPUT_DIR = "ogive_cad"


# ============================================================
# GEOMETRY FUNCTIONS
# ============================================================

def tangent_ogive_parameters(D: float, L: float):
    """Return tangent-ogive generating-circle radius R and x-center xc."""

    if D <= 0 or L <= 0:
        raise ValueError("D and L must be positive.")

    R = D * ((L / D) ** 2 + 0.25)
    xc = -(R - D / 2.0)

    return R, xc


def _single_tag(dimtags, dim: int, description: str):
    """Return the unique Gmsh entity tag of a given dimension."""

    tags = [tag for entity_dim, tag in dimtags if entity_dim == dim]

    if len(tags) != 1:
        raise RuntimeError(
            f"Expected exactly one {description}, got {len(tags)}: {dimtags}"
        )

    return tags[0]


def _create_outer_arc(D: float, L: float):
    """Create the exact tangent-ogive generating arc in the x-z plane."""

    R, xc = tangent_ogive_parameters(D, L)

    p_center = gmsh.model.occ.addPoint(xc, 0.0, 0.0)
    p_base = gmsh.model.occ.addPoint(D / 2.0, 0.0, 0.0)
    p_tip = gmsh.model.occ.addPoint(0.0, 0.0, L)

    outer_arc = gmsh.model.occ.addCircleArc(
        p_base,
        p_center,
        p_tip,
    )

    return outer_arc


def _make_zero_thickness_surface(D: float, L: float):
    """
    Create a zero-thickness ogive surface.

    The first 180-degree surface is generated by revolution,
    then copied and rotated by another 180 degrees.
    """

    outer_arc = _create_outer_arc(D, L)

    revolved = gmsh.model.occ.revolve(
        [(1, outer_arc)],
        0.0, 0.0, 0.0,     # point on rotation axis
        0.0, 0.0, 1.0,     # rotation axis: +z
        math.pi,
    )

    half_surface_1 = _single_tag(
        revolved,
        2,
        "revolved surface",
    )

    copied = gmsh.model.occ.copy([(2, half_surface_1)])
    half_surface_2 = _single_tag(
        copied,
        2,
        "copied surface",
    )

    gmsh.model.occ.rotate(
        [(2, half_surface_2)],
        0.0, 0.0, 0.0,
        0.0, 0.0, 1.0,
        math.pi,
    )

    # Make the two half-surfaces conformal.
    gmsh.model.occ.fragment(
        [(2, half_surface_1)],
        [(2, half_surface_2)],
    )

    gmsh.model.occ.synchronize()

    surfaces = gmsh.model.getEntities(2)
    volumes = gmsh.model.getEntities(3)

    if volumes:
        raise RuntimeError(
            "Zero-thickness CAD unexpectedly contains a volume."
        )

    if not surfaces:
        raise RuntimeError(
            "Zero-thickness ogive surface creation failed."
        )


def _make_wall_section(D: float, L: float, t: float):
    """
    Create the closed x-z cross-section for a finite-thickness ogive.

    The inner ogive is a concentric inward circular offset
    with radius R - t.
    """

    if t <= 0:
        raise ValueError("For finite thickness, t must be > 0.")

    if t >= D / 2.0:
        raise ValueError("Thickness t must be smaller than D/2.")

    R, xc = tangent_ogive_parameters(D, L)

    R_inner = R - t
    cos_theta_inner = (-xc) / R_inner

    if not (0.0 < cos_theta_inner < 1.0):
        raise RuntimeError(
            "Invalid inner-ogive geometry. "
            "Try reducing wall thickness t."
        )

    theta_inner = math.acos(cos_theta_inner)
    z_inner_tip = R_inner * math.sin(theta_inner)

    # Shared center of outer and inner generating circles.
    p_center = gmsh.model.occ.addPoint(xc, 0.0, 0.0)

    # Outer endpoints.
    p_o_base = gmsh.model.occ.addPoint(D / 2.0, 0.0, 0.0)
    p_o_tip = gmsh.model.occ.addPoint(0.0, 0.0, L)

    # Inner endpoints.
    p_i_base = gmsh.model.occ.addPoint(
        xc + R_inner,
        0.0,
        0.0,
    )

    p_i_tip = gmsh.model.occ.addPoint(
        0.0,
        0.0,
        z_inner_tip,
    )

    outer_arc = gmsh.model.occ.addCircleArc(
        p_o_base,
        p_center,
        p_o_tip,
    )

    inner_arc = gmsh.model.occ.addCircleArc(
        p_i_base,
        p_center,
        p_i_tip,
    )

    tip_edge = gmsh.model.occ.addLine(
        p_o_tip,
        p_i_tip,
    )

    base_edge = gmsh.model.occ.addLine(
        p_i_base,
        p_o_base,
    )

    section_loop = gmsh.model.occ.addCurveLoop(
        [
            outer_arc,
            tip_edge,
            -inner_arc,
            base_edge,
        ]
    )

    section_face = gmsh.model.occ.addPlaneSurface(
        [section_loop]
    )

    return section_face, z_inner_tip


def _make_finite_thickness_solid(D: float, L: float, t: float):
    """Create the finite-thickness ogive as one fused 3-D solid."""

    section_face, z_inner_tip = _make_wall_section(
        D,
        L,
        t,
    )

    # First 180-degree half-solid.
    revolved = gmsh.model.occ.revolve(
        [(2, section_face)],
        0.0, 0.0, 0.0,
        0.0, 0.0, 1.0,
        math.pi,
    )

    half_volume_1 = _single_tag(
        revolved,
        3,
        "revolved volume",
    )

    # Copy and rotate the first half by 180 degrees.
    copied = gmsh.model.occ.copy(
        [(3, half_volume_1)]
    )

    half_volume_2 = _single_tag(
        copied,
        3,
        "copied volume",
    )

    gmsh.model.occ.rotate(
        [(3, half_volume_2)],
        0.0, 0.0, 0.0,
        0.0, 0.0, 1.0,
        math.pi,
    )

    # Fuse the two half-solids.
    fused, _ = gmsh.model.occ.fuse(
        [(3, half_volume_1)],
        [(3, half_volume_2)],
    )

    _single_tag(
        fused,
        3,
        "fused ogive volume",
    )

    gmsh.model.occ.synchronize()

    volumes = gmsh.model.getEntities(3)

    if len(volumes) != 1:
        raise RuntimeError(
            f"Expected one final ogive volume, "
            f"got {len(volumes)}: {volumes}"
        )

    return z_inner_tip


# ============================================================
# CAD GENERATION
# ============================================================

def create_ogive_cad(
    D: float,
    L: float,
    t: float = 0.0,
    output_dir="ogive_cad",
):
    """
    Create tangent-ogive CAD and export it as STEP.

    Parameters
    ----------
    D : float
        Outer base diameter [mm].

    L : float
        Outer height [mm].

    t : float
        Wall thickness [mm].
        t = 0.0 -> zero-thickness surface.
        t > 0.0 -> finite-thickness solid.

    output_dir : str or pathlib.Path
        Output folder.

    Returns
    -------
    str
        Absolute path of the generated STEP file.
    """

    if t < 0:
        raise ValueError("Thickness t cannot be negative.")

    R, _ = tangent_ogive_parameters(D, L)

    output_dir = Path(output_dir)
    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    if math.isclose(t, 0.0, abs_tol=1.0e-12):
        file_name = "ogive_t0mm.step"
        model_type = "Zero-thickness surface"
    else:
        file_name = f"ogive_t{t:g}mm.step"
        model_type = "Finite-thickness 3-D solid"

    output_file = (
        output_dir / file_name
    ).resolve()

    gmsh.initialize()

    try:
        gmsh.model.add("ogive_cad")

        if math.isclose(
            t,
            0.0,
            abs_tol=1.0e-12,
        ):
            _make_zero_thickness_surface(
                D,
                L,
            )
            z_inner_tip = None

        else:
            z_inner_tip = _make_finite_thickness_solid(
                D,
                L,
                t,
            )

        gmsh.write(str(output_file))

    finally:
        gmsh.finalize()

    print()
    print("========================================")
    print("Tangent-ogive CAD generation complete")
    print("========================================")
    print(f"Outer D        = {D:.3f} mm")
    print(f"Outer L        = {L:.3f} mm")
    print(f"Ogive R        = {R:.6f} mm")
    print(f"Thickness t    = {t:.3f} mm")
    print(f"Model type     = {model_type}")

    if z_inner_tip is not None:
        print(f"Outer tip z    = {L:.6f} mm")
        print(f"Inner tip z    = {z_inner_tip:.6f} mm")
        print(f"Inner base dia = {D - 2.0 * t:.6f} mm")

    print(f"STEP file      = {output_file}")

    return str(output_file)


# ============================================================
# RUN DIRECTLY
# ============================================================

if __name__ == "__main__":

    create_ogive_cad(
        D=D,
        L=L,
        t=t,
        output_dir=OUTPUT_DIR,
    )
