"""기존 원호·반회전 방식의 tangent-ogive 생성. 호출자가 Gmsh 세션을 관리한다."""
from __future__ import annotations

import math
import gmsh

def tangent_ogive_parameters(D: float, L: float):
    """Return tangent-ogive generating-circle radius R and x-center xc."""

    if D <= 0 or L <= 0:
        raise ValueError("D and L must be positive.")

    R = D * ((L / D) ** 2 + 0.25)
    xc = -(R - D / 2.0)

    return R, xc


def _single_tag(dimtags, dim: int, description: str):
    """Return the unique Gmsh entity tag of a given dimension."""

    tags = [tag for entity_dim, tag in dimtags if entity_dim == dim]

    if len(tags) != 1:
        raise RuntimeError(
            f"Expected exactly one {description}, got {len(tags)}: {dimtags}"
        )

    return tags[0]


def _create_outer_arc(D: float, L: float):
    """Create the exact tangent-ogive generating arc in the x-z plane."""

    R, xc = tangent_ogive_parameters(D, L)

    p_center = gmsh.model.occ.addPoint(xc, 0.0, 0.0)
    p_base = gmsh.model.occ.addPoint(D / 2.0, 0.0, 0.0)
    p_tip = gmsh.model.occ.addPoint(0.0, 0.0, L)

    outer_arc = gmsh.model.occ.addCircleArc(
        p_base,
        p_center,
        p_tip,
    )

    return outer_arc


def _make_zero_thickness_surface(D: float, L: float):
    """
    Create a zero-thickness ogive surface.

    The first 180-degree surface is generated by revolution,
    then copied and rotated by another 180 degrees.
    """

    outer_arc = _create_outer_arc(D, L)

    revolved = gmsh.model.occ.revolve(
        [(1, outer_arc)],
        0.0, 0.0, 0.0,     # point on rotation axis
        0.0, 0.0, 1.0,     # rotation axis: +z
        math.pi,
    )

    half_surface_1 = _single_tag(
        revolved,
        2,
        "revolved surface",
    )

    copied = gmsh.model.occ.copy([(2, half_surface_1)])
    half_surface_2 = _single_tag(
        copied,
        2,
        "copied surface",
    )

    gmsh.model.occ.rotate(
        [(2, half_surface_2)],
        0.0, 0.0, 0.0,
        0.0, 0.0, 1.0,
        math.pi,
    )

    # Make the two half-surfaces conformal.
    joined, _ = gmsh.model.occ.fragment(
        [(2, half_surface_1)],
        [(2, half_surface_2)],
    )

    gmsh.model.occ.synchronize()

    surfaces = [dt for dt in joined if dt[0] == 2]
    if not surfaces:
        raise RuntimeError("Zero-thickness ogive surface creation failed.")
    return surfaces


def _make_wall_section(D: float, L: float, t: float):
    """
    Create the closed x-z cross-section for a finite-thickness ogive.

    The inner ogive is a concentric inward circular offset
    with radius R - t.
    """

    if t <= 0:
        raise ValueError("For finite thickness, t must be > 0.")

    if t >= D / 2.0:
        raise ValueError("Thickness t must be smaller than D/2.")

    R, xc = tangent_ogive_parameters(D, L)

    R_inner = R - t
    cos_theta_inner = (-xc) / R_inner

    if not (0.0 < cos_theta_inner < 1.0):
        raise RuntimeError(
            "Invalid inner-ogive geometry. "
            "Try reducing wall thickness t."
        )

    theta_inner = math.acos(cos_theta_inner)
    z_inner_tip = R_inner * math.sin(theta_inner)

    # Shared center of outer and inner generating circles.
    p_center = gmsh.model.occ.addPoint(xc, 0.0, 0.0)

    # Outer endpoints.
    p_o_base = gmsh.model.occ.addPoint(D / 2.0, 0.0, 0.0)
    p_o_tip = gmsh.model.occ.addPoint(0.0, 0.0, L)

    # Inner endpoints.
    p_i_base = gmsh.model.occ.addPoint(
        xc + R_inner,
        0.0,
        0.0,
    )

    p_i_tip = gmsh.model.occ.addPoint(
        0.0,
        0.0,
        z_inner_tip,
    )

    outer_arc = gmsh.model.occ.addCircleArc(
        p_o_base,
        p_center,
        p_o_tip,
    )

    inner_arc = gmsh.model.occ.addCircleArc(
        p_i_base,
        p_center,
        p_i_tip,
    )

    tip_edge = gmsh.model.occ.addLine(
        p_o_tip,
        p_i_tip,
    )

    base_edge = gmsh.model.occ.addLine(
        p_i_base,
        p_o_base,
    )

    section_loop = gmsh.model.occ.addCurveLoop(
        [
            outer_arc,
            tip_edge,
            -inner_arc,
            base_edge,
        ]
    )

    section_face = gmsh.model.occ.addPlaneSurface(
        [section_loop]
    )

    return section_face, z_inner_tip


def _make_finite_thickness_solid(D: float, L: float, t: float):
    """Create the finite-thickness ogive as one fused 3-D solid."""

    section_face, z_inner_tip = _make_wall_section(
        D,
        L,
        t,
    )

    # First 180-degree half-solid.
    revolved = gmsh.model.occ.revolve(
        [(2, section_face)],
        0.0, 0.0, 0.0,
        0.0, 0.0, 1.0,
        math.pi,
    )

    half_volume_1 = _single_tag(
        revolved,
        3,
        "revolved volume",
    )

    # Copy and rotate the first half by 180 degrees.
    copied = gmsh.model.occ.copy(
        [(3, half_volume_1)]
    )

    half_volume_2 = _single_tag(
        copied,
        3,
        "copied volume",
    )

    gmsh.model.occ.rotate(
        [(3, half_volume_2)],
        0.0, 0.0, 0.0,
        0.0, 0.0, 1.0,
        math.pi,
    )

    # Fuse the two half-solids.
    fused, _ = gmsh.model.occ.fuse(
        [(3, half_volume_1)],
        [(3, half_volume_2)],
    )

    _single_tag(
        fused,
        3,
        "fused ogive volume",
    )

    gmsh.model.occ.synchronize()

    return [dt for dt in fused if dt[0] == 3], z_inner_tip


def build(D: float, L: float, t: float = 0.0, origin=(0.0, 0.0, 0.0)):
    """현재 OCC 모델에 ogive를 추가하고 최상위 entity를 반환한다. STEP은 생성하지 않는다."""
    before = set(gmsh.model.occ.getEntities())
    if t == 0:
        roots = _make_zero_thickness_surface(D, L)
    else:
        roots, _ = _make_finite_thickness_solid(D, L, t)
    gmsh.model.occ.synchronize()
    # 원호 중심·단면 등 생성용 entity가 bbox와 메시 크기에 섞이지 않도록 제거한다.
    keep = set(roots)
    pending = list(roots)
    while pending:
        entity = pending.pop()
        if entity[0] == 0:
            continue
        for dim, tag in gmsh.model.getBoundary([entity], oriented=False):
            child = (dim, abs(tag))
            if child not in keep:
                keep.add(child)
                pending.append(child)
    for dim in (2, 1, 0):
        unused = [dt for dt in gmsh.model.occ.getEntities(dim) if dt not in before and dt not in keep]
        if unused:
            gmsh.model.occ.remove(unused, recursive=False)
    if any(origin):
        gmsh.model.occ.translate(roots, *origin)
    gmsh.model.occ.synchronize()
    return roots
